// <auto-generated />
using System;
using LinqEtSeedEF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinqEtSeedEF.Migrations
{
    [DbContext(typeof(LinqEtSeedEFContext))]
    [Migration("20260925132327_ajoutCommande")]
    partial class ajoutCommande
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LinqEtSeedEF.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Client");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "123 rue Principale, Montréal",
                            Nom = "Marie-Josée Tremblay",
                            Telephone = "(514) 555-1234"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "456 boulevard Saint-Laurent, Québec",
                            Nom = "Patrick Gagné",
                            Telephone = "(418) 555-5678"
                        },
                        new
                        {
                            Id = 3,
                            Adresse = "789 avenue des Érables, Trois-Rivières",
                            Nom = "Sophie Dubois",
                            Telephone = "(819) 555-9012"
                        },
                        new
                        {
                            Id = 4,
                            Adresse = "1010 rue Saint-Denis, Montréal",
                            Nom = "Jean-François Lavoie",
                            Telephone = "(514) 555-3456"
                        },
                        new
                        {
                            Id = 5,
                            Adresse = "111 rue des Pionniers, Québec",
                            Nom = "Geneviève Parent",
                            Telephone = "(418) 555-7890"
                        });
                });

            modelBuilder.Entity("LinqEtSeedEF.Models.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Commande");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            Date = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            Date = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 3,
                            Date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 2,
                            Date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RestaurantId = 4
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 2,
                            Date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RestaurantId = 2
                        });
                });

            modelBuilder.Entity("LinqEtSeedEF.Models.CommandePlat", b =>
                {
                    b.Property<int>("PlatId")
                        .HasColumnType("int");

                    b.Property<int>("CommandeId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("PlatId", "CommandeId");

                    b.HasIndex("CommandeId");

                    b.ToTable("CommandePlat");

                    b.HasData(
                        new
                        {
                            PlatId = 1,
                            CommandeId = 1,
                            Quantite = 1
                        },
                        new
                        {
                            PlatId = 2,
                            CommandeId = 1,
                            Quantite = 2
                        },
                        new
                        {
                            PlatId = 3,
                            CommandeId = 2,
                            Quantite = 2
                        },
                        new
                        {
                            PlatId = 4,
                            CommandeId = 2,
                            Quantite = 1
                        },
                        new
                        {
                            PlatId = 5,
                            CommandeId = 3,
                            Quantite = 4
                        },
                        new
                        {
                            PlatId = 6,
                            CommandeId = 4,
                            Quantite = 2
                        },
                        new
                        {
                            PlatId = 3,
                            CommandeId = 5,
                            Quantite = 3
                        },
                        new
                        {
                            PlatId = 4,
                            CommandeId = 5,
                            Quantite = 3
                        });
                });

            modelBuilder.Entity("LinqEtSeedEF.Models.Plat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<bool>("Vegetarien")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Plat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Un mélange de légumes frais sautés à la poêle",
                            Nom = "Sauté de légumes",
                            Prix = 8.99m,
                            RestaurantId = 1,
                            Vegetarien = true
                        },
                        new
                        {
                            Id = 2,
                            Description = "Du riz blanc servi avec des carottes fraîches",
                            Nom = "Riz aux carottes",
                            Prix = 6.99m,
                            RestaurantId = 1,
                            Vegetarien = true
                        },
                        new
                        {
                            Id = 3,
                            Description = "Un délicieux plat de poulet avec du gingembre frais",
                            Nom = "Poulet au gingembre",
                            Prix = 12.99m,
                            RestaurantId = 2,
                            Vegetarien = false
                        },
                        new
                        {
                            Id = 4,
                            Description = "Un délicieux plat de tofu avec du gingembre frais",
                            Nom = "Tofu au gingembre",
                            Prix = 11.99m,
                            RestaurantId = 2,
                            Vegetarien = true
                        },
                        new
                        {
                            Id = 5,
                            Description = "Patate, sauce, fromage skwich skwich",
                            Nom = "Poutine",
                            Prix = 7.99m,
                            RestaurantId = 3,
                            Vegetarien = false
                        },
                        new
                        {
                            Id = 6,
                            Description = "Pepperonni fromage",
                            Nom = "Pizza",
                            Prix = 9.99m,
                            RestaurantId = 4,
                            Vegetarien = false
                        });
                });

            modelBuilder.Entity("LinqEtSeedEF.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restaurant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "456 rue Sainte-Catherine, Montréal",
                            Nom = "La graine du père George",
                            Telephone = "(514) 555-2345"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "789 rue Principale, Québec",
                            Nom = "Le Bistro",
                            Telephone = "(418) 555-6789"
                        },
                        new
                        {
                            Id = 3,
                            Adresse = "1010 boulevard René-Lévesque, Trois-Rivières",
                            Nom = "La Belle Province",
                            Telephone = "(819) 555-2345"
                        },
                        new
                        {
                            Id = 4,
                            Adresse = "1111 rue de la Montagne, Montréal",
                            Nom = "La Piazzetta",
                            Telephone = "(514) 555-6789"
                        },
                        new
                        {
                            Id = 5,
                            Adresse = "2222 rue Saint-Jean, Québec",
                            Nom = "Le Petit Coin",
                            Telephone = "(418) 555-2345"
                        });
                });

            modelBuilder.Entity("LinqEtSeedEF.Models.TestData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ValeurA")
                        .HasColumnType("int");

                    b.Property<int>("ValeurB")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TestData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ValeurA = 1,
                            ValeurB = 379
                        },
                        new
                        {
                            Id = 2,
                            ValeurA = 85,
                            ValeurB = 65000
                        });
                });

            modelBuilder.Entity("LinqEtSeedEF.Models.Commande", b =>
                {
                    b.HasOne("LinqEtSeedEF.Models.Client", "Client")
                        .WithMany("Commandes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinqEtSeedEF.Models.Restaurant", "Restaurant")
                        .WithMany("Commandes")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("LinqEtSeedEF.Models.CommandePlat", b =>
                {
                    b.HasOne("LinqEtSeedEF.Models.Commande", "Commande")
                        .WithMany("CommandesPlats")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LinqEtSeedEF.Models.Plat", "Plat")
                        .WithMany("CommandesPlats")
                        .HasForeignKey("PlatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Plat");
                });

            modelBuilder.Entity("LinqEtSeedEF.Models.Plat", b =>
                {
                    b.HasOne("LinqEtSeedEF.Models.Restaurant", "Restaurant")
                        .WithMany("Plats")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("LinqEtSeedEF.Models.Client", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("LinqEtSeedEF.Models.Commande", b =>
                {
                    b.Navigation("CommandesPlats");
                });

            modelBuilder.Entity("LinqEtSeedEF.Models.Plat", b =>
                {
                    b.Navigation("CommandesPlats");
                });

            modelBuilder.Entity("LinqEtSeedEF.Models.Restaurant", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Plats");
                });
#pragma warning restore 612, 618
        }
    }
}
